export const LOGIN_API_CALL_REQUEST = 'LOGIN_API_CALL_REQUEST';
export const LOGIN_API_CALL_SUCCESS = 'LOGIN_API_CALL_SUCCESS';
export const LOGIN_API_CALL_FAILURE = 'LOGIN_API_CALL_FAILURE';

export const DRAWER_LOGIN = 'DRAWER_LOGIN';