export const LOGIN_API_CALL_REQUEST = 'LOGIN_API_CALL_REQUEST';
export const LOGIN_API_CALL_SUCCESS = 'LOGIN_API_CALL_SUCCESS';
export const LOGIN_API_CALL_FAILURE = 'LOGIN_API_CALL_FAILURE';

export const DRAWER_LOGIN = 'DRAWER_LOGIN';

export const DRAWER_CREATE_USER = 'DRAWER_CREATE_USER';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const CLEAN_FORM = 'CLEAN_FORM';