export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = 'GET_PRODUCTS_BY_CATEGORY_REQUEST';
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const GET_PRODUCTS_BY_CATEGORY_FAILURE = 'GET_PRODUCTS_BY_CATEGORY_FAILURE';

export const DRAWER_BAG = 'DRAWER_BAG';
export const DRAWER_BAG_DETAIL = 'DRAWER_BAG_DETAIL';

export const UPDATE_BAG_PRODUCTS = 'UPDATE_BAG_PRODUCTS';